<?php
namespace Tests;
use Lib\Models\User;

abstract class TestCase extends \Illuminate\Foundation\Testing\TestCase
{
    /**
     * The base URL to use while testing the application.
     *
     * @var string
     */
    protected $baseUrl = 'http://localhost';

    /**
     * Creates the application.
     *
     * @return \Illuminate\Foundation\Application
     */
    public function createApplication()
    {
      //just create the database here you know?
        \touch(__DIR__."/../database/testing.sqlite");
        $app = require __DIR__.'/../bootstrap/app.php';

        $app->make(\Illuminate\Contracts\Console\Kernel::class)->bootstrap();

        return $app;
    }
    protected function createDefaultUser()
    {
      return User::create([
        "email"=>"root@localhost",
        "phone_number"=>"",
        "sex"=>true,
        "accesstoken"=>"root",
        "firstname"=>"root",
        "name"=>"rootsey",
        "lastname"=>"toor",
        "password"=>bcrypt("root"),
      ]);
    }
//    public function tearDown()
//    {
//      parent::tearDown(); // TODO: Change the autogenerated stub
//      unlink(__DIR__."/../database/testing.sqlite");
//    }

}
