<?php

namespace Tests\Feature\Api;

use Lib\Models\Car;
use Lib\Models\CarType;
use Lib\Models\Run;
use Lib\Models\User;
use Lib\Models\Waypoint;
use \Tests\TestCase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class AddCarsToRun extends TestCase
{
    use DatabaseMigrations;
    public function setUp()
    {
      parent::setUp(); // TODO: Change the autogenerated stub
      //create a user to authenticate
      $this->createDefaultUser();
    }
    /**
     * @test
     */
    public function addCarToRun()
    {
      /**
       * @var $run Run
       */
      $run = factory(Run::class)->create();
      $car = factory(Car::class)->create();
      $res = $this->json("POST","/api/runs/{$run->id}/runners",["car"=>$car->id], ["x-access-token"=>"root"]);
      $res->assertStatus(200);
      $this->assertEquals($run->subscriptions()->getResults()->count(),1);//there must only be one subscription
      
      //var_dump(Run::find(1)->subscriptions()->first());
      $this->assertNotNull($run->subscriptions()->getResults()->first()->car);
      $this->assertEquals($run->subscriptions()->getResults()->first()->car->id,$car->id);

    }

  /**
   * @test
   */
    public function addCarTypeToRun()
    {
      /**
       * @var $run Run
       */
      $run = factory(Run::class)->create();
      $car_type = factory(CarType::class)->create();
      $res = $this->json("POST","/api/runs/{$run->id}/runners",["car_type"=>$car_type->id], ["x-access-token"=>"root"]);
      $res->assertStatus(200);
      $this->assertEquals($run->subscriptions()->getResults()->count(),1);//there must only be one subscription
      $this->assertNotNull($run->subscriptions()->getResults()->first()->car_type);
      $this->assertEquals($run->subscriptions()->getResults()->first()->car_type->id,$car_type->id);
    }
  /**
   * @test
   */
  public function addUserToRun()
  {
    /**
     * @var $run Run
     */
    $run = factory(Run::class)->create();
    $user = factory(User::class)->create();
    $res = $this->json("POST","/api/runs/{$run->id}/runners",["user"=>$user->id], ["x-access-token"=>"root"]);
    $res->assertStatus(200);
    $this->assertEquals($run->subscriptions()->getResults()->count(),1);//there must only be one subscription
    $this->assertNotNull($run->subscriptions()->getResults()->first()->user);
    $this->assertEquals($run->subscriptions()->getResults()->first()->user->id,$user->id);
  }
}
